// src/screens/ApplyPermission/ApplyPermissionScreen.styles.js
import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#EEF4FB',
  },
  scrollContent: {
    paddingBottom: 140,
  },

  /* Header Banner - Flush to top with vibrant blue gradient */
  headerBanner: {
    backgroundColor: '#0066FF',
    paddingTop: Platform.OS === 'ios' ? 44 : 20,
    paddingHorizontal: 20,
    paddingBottom: 44,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    position: 'relative',
    overflow: 'hidden',
  },
  decorCircle1: {
    position: 'absolute',
    top: -30,
    right: -20,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
  },
  decorCircle2: {
    position: 'absolute',
    bottom: -30,
    left: -20,
    width: 170,
    height: 170,
    borderRadius: 85,
    backgroundColor: 'rgba(255, 255, 255, 0.09)',
  },
  backBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 14,
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  headerLeft: {
    flex: 1,
    paddingRight: 10,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.3,
  },
  headerSubtitle: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.88)',
    marginTop: 4,
    fontWeight: '400',
  },

  /* 3D Calendar Illustration Badge */
  badgeContainer: {
    alignItems: 'flex-end',
    marginTop: -28,
  },
  calendarIllustrateBox: {
    width: 66,
    height: 58,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    position: 'relative',
    shadowColor: '#002070',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.28,
    shadowRadius: 14,
    elevation: 6,
    overflow: 'visible',
  },
  calendarHeaderBar: {
    height: 15,
    backgroundColor: '#3B82F6',
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
  },
  calendarRingsRow: {
    position: 'absolute',
    top: -5,
    left: 8,
    right: 8,
    flexDirection: 'row',
    justifyContent: 'space-around',
    zIndex: 2,
  },
  calendarRing: {
    width: 5,
    height: 11,
    borderRadius: 2.5,
    backgroundColor: '#BFDBFE',
  },
  calendarGrid: {
    padding: 6,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  calendarCell: {
    width: 7,
    height: 7,
    borderRadius: 2,
    backgroundColor: '#BFDBFE',
    opacity: 0.85,
  },
  clockBadge: {
    position: 'absolute',
    bottom: -6,
    right: -8,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#0066FF',
    borderWidth: 3,
    borderColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },

  /* Form Container Card */
  formCard: {
    marginHorizontal: 14,
    marginTop: -24,
    backgroundColor: '#FFFFFF',
    borderRadius: 26,
    paddingHorizontal: 16,
    paddingVertical: 22,
    paddingBottom: 32,
    marginBottom: 36,
    shadowColor: '#0F1E50',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.07,
    shadowRadius: 20,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(226, 232, 240, 0.8)',
  },

  field: {
    marginBottom: 18,
  },
  label: {
    fontSize: 13.5,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 8,
  },
  required: {
    color: '#EF4444',
  },

  /* Card Inputs and Select Boxes */
  inputCard: {
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    paddingHorizontal: 16,
    backgroundColor: '#FFFFFF',
  },
  cardInput: {
    flex: 1,
    fontSize: 14.5,
    color: '#111827',
    fontWeight: '500',
  },
  selectCard: {
    height: 52,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    paddingHorizontal: 16,
    backgroundColor: '#FFFFFF',
  },
  selectCardActive: {
    borderColor: '#0066FF',
    shadowColor: '#0066FF',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 2,
  },
  selectText: {
    fontSize: 14.5,
    color: '#111827',
    fontWeight: '500',
  },

  /* Dropdown Menu */
  dropdownContainer: {
    marginTop: 6,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
  },
  dropdownOption: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  dropdownOptionSelected: {
    backgroundColor: '#EFF6FF',
  },
  dropdownOptionText: {
    fontSize: 14,
    color: '#111827',
    fontWeight: '500',
  },
  dropdownOptionTextSelected: {
    color: '#0066FF',
    fontWeight: '700',
  },

  /* Reason Textarea Card */
  textareaCard: {
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 30,
    position: 'relative',
  },
  textArea: {
    fontSize: 14.5,
    color: '#111827',
    minHeight: 68,
    textAlignVertical: 'top',
    padding: 0,
    lineHeight: 20,
  },
  charCounter: {
    position: 'absolute',
    right: 16,
    bottom: 8,
    fontSize: 12,
    color: '#94A3B8',
    fontWeight: '500',
  },

  /* Submit Button */
  submitBtn: {
    height: 52,
    backgroundColor: '#0066FF',
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    marginTop: 20,
    marginBottom: 12,
    shadowColor: '#0066FF',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.38,
    shadowRadius: 14,
    elevation: 5,
  },
  submitIcon: {
    marginRight: 4,
  },
  submitText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
});
