// src/screens/LeaveApprovalDetail/LeaveApprovalDetailScreen.styles.js
import { StyleSheet } from 'react-native';
import { colors, spacing, radius } from '../../theme/theme';

export default StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  scrollContent: { paddingHorizontal: spacing.lg, paddingBottom: spacing.xxl },
  employeeCard: { marginBottom: spacing.lg },
  employeeRow: { flexDirection: 'row', gap: spacing.md, alignItems: 'center' },
  name: { fontSize: 19, fontWeight: '800', color: colors.textPrimary },
  role: { color: colors.textSecondary, marginTop: 2 },
  empId: { color: colors.primary, fontWeight: '700', marginTop: 4, fontSize: 13 },
  specsCard: { marginBottom: spacing.lg },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textMuted,
    letterSpacing: 0.5,
    marginBottom: spacing.md,
  },
  detailRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: spacing.sm },
  detailLabel: { color: colors.textSecondary },
  detailValue: { color: colors.textPrimary, fontWeight: '600' },
  detailValueLink: { color: colors.primary, fontWeight: '700' },
  detailValueBold: { fontWeight: '800' },
  reasonBlock: {
    marginTop: spacing.md,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.divider,
  },
  reasonLabel: { color: colors.textSecondary, marginBottom: spacing.sm },
  reasonText: { color: colors.textPrimary, lineHeight: 21 },
  pathCard: { marginBottom: spacing.lg },
  pathRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: spacing.sm },
  pathDone: { color: colors.success, fontWeight: '700' },
  pathPending: { color: colors.warning, fontWeight: '700' },
  pathFuture: { color: colors.textSecondary, fontWeight: '600' },
  pathArrow: { color: colors.textMuted },
  remarksLabel: { fontSize: 15, fontWeight: '700', color: colors.textPrimary, marginBottom: spacing.sm },
  remarksInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing.lg,
    minHeight: 90,
    textAlignVertical: 'top',
    backgroundColor: colors.surface,
    marginBottom: spacing.lg,
    fontSize: 15,
    color: colors.textPrimary,
  },
  actionsRow: { flexDirection: 'row', gap: spacing.md },
  rejectBtn: {
    flex: 1,
    borderWidth: 1.5,
    borderColor: colors.dangerBg,
    backgroundColor: colors.surface,
    borderRadius: radius.pill,
    paddingVertical: spacing.lg,
    alignItems: 'center',
  },
  rejectText: { color: colors.danger, fontWeight: '800' },
  approveBtn: {
    flex: 1,
    backgroundColor: colors.primary,
    borderRadius: radius.pill,
    paddingVertical: spacing.lg,
    alignItems: 'center',
  },
  approveText: { color: '#fff', fontWeight: '800' },
});
