// src/screens/EmployeeDashboard/EmployeeDashboardScreen.styles.js
import { StyleSheet } from 'react-native';
import { colors, spacing, radius } from '../../theme/theme';

export default StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  scrollContent: { paddingBottom: spacing.xxl },
  topRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
  },
  brandRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  logo: { width: 30, height: 30 },
  brandName: { fontSize: 20, fontWeight: '800', color: colors.textPrimary },
  bellButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.infoBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bellDot: {
    position: 'absolute',
    top: 10,
    right: 12,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.danger,
  },
  companyName: {
    color: colors.textSecondary,
    paddingHorizontal: spacing.lg,
    marginTop: spacing.xs,
  },
  greetingBlock: {
    paddingHorizontal: spacing.lg,
    marginTop: spacing.xl,
    marginBottom: spacing.lg,
  },
  greeting: { fontSize: 24, fontWeight: '800', color: colors.textPrimary },
  date: { color: colors.textSecondary, marginTop: 4 },
  attendanceCard: { marginHorizontal: spacing.lg, marginBottom: spacing.lg },
  attendanceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  statusDotRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  statusDot: { width: 10, height: 10, borderRadius: 5 },
  attendanceText: { fontSize: 16, fontWeight: '700', color: colors.textPrimary },
  checkOutBtn: {
    backgroundColor: colors.dangerBg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.pill,
  },
  checkOutText: { color: colors.danger, fontWeight: '700' },
  divider: { height: 1, backgroundColor: colors.divider, marginVertical: spacing.md },
  statsRow: { flexDirection: 'row', justifyContent: 'space-between' },
  statLabel: { color: colors.textSecondary, fontSize: 13, marginBottom: 4 },
  statValue: { fontSize: 20, fontWeight: '800', color: colors.textPrimary },
  balancesCard: { marginHorizontal: spacing.lg, marginBottom: spacing.lg },
  cardTitle: { fontSize: 18, fontWeight: '800', color: colors.textPrimary, marginBottom: spacing.md },
  balanceItem: { marginBottom: spacing.md },
  balanceHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  balanceLabel: { color: colors.textPrimary, fontSize: 15 },
  balanceValue: { color: colors.primary, fontWeight: '700' },
  progressTrack: {
    height: 8,
    backgroundColor: colors.divider,
    borderRadius: 4,
    overflow: 'hidden',
  },
  progressFill: { height: '100%', backgroundColor: colors.primary, borderRadius: 4 },
  sectionLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textMuted,
    letterSpacing: 0.5,
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.sm,
    marginTop: spacing.sm,
  },
  quickActionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: spacing.lg,
    gap: spacing.md,
    marginBottom: spacing.lg,
  },
  quickAction: {
    width: '47%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: colors.infoBg,
    borderRadius: radius.md,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
  },
  quickActionText: { color: colors.primary, fontWeight: '700', fontSize: 13 },
  requestCard: { marginHorizontal: spacing.lg, marginBottom: spacing.md },
  requestRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  requestTitle: { fontSize: 16, fontWeight: '700', color: colors.textPrimary },
  requestSubtitle: { color: colors.textSecondary, marginTop: 4, fontSize: 13 },
});
