// src/screens/EmployeeDashboard/EmployeeDashboardScreen.styles.js
import { StyleSheet, Dimensions } from 'react-native';
import { colors, spacing, radius } from '../../theme/theme';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F4F7FB' },
  scrollContent: { paddingBottom: 100 },

  // ── Header (Deep Blue Gradient Style matching Image 2, Aligned Upward) ──
  dashHeader: {
    backgroundColor: '#0A4FD5',
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 22,
    marginTop: 0,
    shadowColor: '#0A4FD5',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 8,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  menuButton: {
    padding: 6,
    borderRadius: 8,
  },
  brandBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  brandLogo: {
    width: 24,
    height: 24,
    resizeMode: 'contain',
  },
  headerDashboardTitleWrap: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerDashboardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: -0.2,
  },
  headerDashboardCircle: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: '#FFFFFF',
    marginTop: 3,
  },

  bellWrapper: {
    position: 'relative',
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bellGlowRing: {
    position: 'absolute',
    top: -4,
    left: -4,
    right: -4,
    bottom: -4,
    borderRadius: 23,
    backgroundColor: 'rgba(77, 150, 255, 0.45)',
    borderWidth: 1.5,
    borderColor: 'rgba(147, 197, 253, 0.8)',
  },
  bellButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#0B2568',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bellDot: {
    position: 'absolute',
    top: 3,
    right: 4,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#EF4444',
    borderWidth: 1.5,
    borderColor: '#0B2568',
  },

  // ── Profile & Greeting Row ──
  headerProfileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  profileGreetingCol: {
    flex: 1,
  },
  greetingHello: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.9)',
    fontWeight: '400',
  },
  greetingName: {
    fontSize: 24,
    fontWeight: '800',
    color: '#FFFFFF',
    marginVertical: 2,
    letterSpacing: -0.3,
  },
  roleMeta: {
    fontSize: 12.5,
    color: 'rgba(255,255,255,0.85)',
    fontWeight: '500',
    marginBottom: 8,
  },
  dateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  dateText: {
    fontSize: 12.5,
    color: 'rgba(255,255,255,0.9)',
    fontWeight: '500',
  },

  avatarBlock: {
    alignItems: 'center',
    marginLeft: 12,
  },
  avatarCircle: {
    width: 74,
    height: 74,
    borderRadius: 37,
    backgroundColor: '#EBF3FE',
    borderWidth: 3.5,
    borderColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 14,
    elevation: 4,
  },
  avatarCaption: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.92)',
    fontWeight: '500',
    marginTop: 6,
  },
  avatarUnderline: {
    width: 22,
    height: 2,
    backgroundColor: '#93C5FD',
    borderRadius: 1,
    marginTop: 3,
  },

  // ── 4 Action Cards (2x2 Grid) - Level Top Edges & Uniform Heights ──
  actionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: 16,
    marginTop: 14,
    marginBottom: 14,
    gap: 12,
  },
  actionCard: {
    width: (width - 44) / 2,
    height: 126,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#EAEFF5',
    padding: 14,
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.025,
    shadowRadius: 8,
    elevation: 2,
  },
  actionTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  actionIconBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  actionChevron: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionTextCol: {
    marginTop: 10,
  },
  actionTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.2,
  },
  actionSubtitle: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 3,
    fontWeight: '500',
  },

  // ── Leave Balances Card ──
  balancesCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#EAEFF5',
    marginHorizontal: 16,
    marginBottom: 14,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.025,
    shadowRadius: 8,
    elevation: 2,
  },
  balancesHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 14,
  },
  balancesTitle: {
    fontSize: 15.5,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.2,
  },
  balanceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 13,
  },
  balanceIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
  },
  balanceCol: {
    flex: 1,
  },
  balanceTopLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
  },
  balanceLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0F172A',
  },
  balanceValue: {
    fontSize: 12,
    fontWeight: '700',
    color: '#2563EB',
  },
  balanceSubLabel: {
    fontSize: 10.5,
    color: '#64748B',
    marginTop: 1,
    marginBottom: 6,
  },
  progressTrack: {
    width: '100%',
    height: 7,
    backgroundColor: '#E2E8F0',
    borderRadius: 4,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#1D4ED8',
    borderRadius: 4,
  },

  // ── Recent Requests Section & Card (Image 5) ──
  recentRequestsSection: {
    marginHorizontal: 16,
    marginBottom: 14,
  },
  sectionLabel: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#94A3B8',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    paddingHorizontal: 4,
    marginBottom: 8,
  },
  recentRequestCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#EAEFF5',
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.025,
    shadowRadius: 8,
    elevation: 2,
    marginBottom: 10,
  },
  recentRequestLeft: {
    flex: 1,
    paddingRight: 8,
  },
  recentRequestTitle: {
    fontSize: 14.5,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.2,
  },
  recentRequestSub: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '500',
    marginTop: 2,
  },
  recentRequestMeta: {
    fontSize: 11,
    color: '#64748B',
    fontWeight: '500',
    marginTop: 2,
  },
  recentRequestRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  recentRequestBadge: {
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
  },
  recentRequestBadgeText: {
    color: '#16A34A',
    fontSize: 11.5,
    fontWeight: '700',
  },
  recentRequestDismissBtn: {
    padding: 4,
  },

  // ── Sidebar Drawer Overlay & Menu (Image 4) ──
  sidebarModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(10, 15, 29, 0.65)',
    flexDirection: 'row',
  },
  sidebarDrawer: {
    width: Math.min(width * 0.82, 300),
    height: '100%',
    backgroundColor: '#1B2333',
    paddingHorizontal: 18,
    paddingTop: 44,
    paddingBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 10, height: 0 },
    shadowOpacity: 0.45,
    shadowRadius: 20,
    elevation: 16,
  },
  sidebarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 18,
  },
  sidebarBrand: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  sidebarLogo: {
    width: 24,
    height: 24,
    resizeMode: 'contain',
  },
  sidebarTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: -0.2,
  },
  sidebarCloseBtn: {
    padding: 6,
    borderRadius: 8,
  },

  sidebarProfileCard: {
    backgroundColor: '#242E42',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: 16,
    padding: 14,
    marginVertical: 18,
  },
  sidebarProfileTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  sidebarAvatarCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#2F6BFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sidebarInitials: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 15,
  },
  sidebarProfileInfo: {
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  sidebarProfileName: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  sidebarRoleBadge: {
    backgroundColor: '#E3F8EE',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    marginTop: 4,
  },
  sidebarRoleText: {
    color: '#059669',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
  },

  sidebarLogoutBtn: {
    marginTop: 12,
    backgroundColor: '#413243',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.25)',
    borderRadius: 10,
    paddingVertical: 9,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  sidebarLogoutText: {
    color: '#F87171',
    fontSize: 13,
    fontWeight: '700',
  },

  sidebarNav: {
    flexDirection: 'column',
    gap: 4,
  },
  sidebarNavItem: {
    width: '100%',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    marginVertical: 2,
  },
  sidebarNavItemText: {
    color: '#CBD5E1',
    fontSize: 14,
    fontWeight: '500',
  },
  sidebarNavItemActive: {
    backgroundColor: '#2F6BFF',
  },
  sidebarNavItemActiveText: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  sidebarNavItemHighlight: {
    backgroundColor: '#2B3448',
  },
  sidebarNavItemHighlightText: {
    color: '#FFFFFF',
  },
});
