// src/screens/ApplyLeave/ApplyLeaveScreen.styles.js
import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#EEF3FA',
  },
  scrollContent: {
    paddingBottom: 110,
  },

  /* Header Banner - Flush to top with no gap */
  headerBanner: {
    backgroundColor: '#175CFF',
    paddingTop: Platform.OS === 'ios' ? 44 : 20,
    paddingHorizontal: 20,
    paddingBottom: 38,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  backBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 14,
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  headerLeft: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.2,
  },
  headerSubtitle: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.85)',
    marginTop: 4,
    fontWeight: '400',
  },

  /* 3D Calendar Illustration Badge */
  badgeContainer: {
    alignItems: 'flex-end',
    marginTop: -28,
  },
  calendarIllustrateBox: {
    width: 62,
    height: 54,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    position: 'relative',
    shadowColor: '#0A2566',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 6,
    overflow: 'visible',
  },
  calendarHeaderBar: {
    height: 14,
    backgroundColor: '#3B82F6',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
  },
  calendarRingsRow: {
    position: 'absolute',
    top: -5,
    left: 8,
    right: 8,
    flexDirection: 'row',
    justifyContent: 'space-around',
    zIndex: 2,
  },
  calendarRing: {
    width: 6,
    height: 10,
    borderRadius: 3,
    backgroundColor: '#93C5FD',
  },
  calendarGrid: {
    padding: 6,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  calendarCell: {
    width: 7,
    height: 7,
    borderRadius: 2,
    backgroundColor: '#BFDBFE',
  },
  calendarCellPrimary: {
    backgroundColor: '#2563EB',
  },
  clockBadge: {
    position: 'absolute',
    bottom: -6,
    right: -8,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#1D4ED8',
    borderWidth: 2.5,
    borderColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  quoteBox: {
    alignItems: 'flex-end',
    marginTop: 10,
  },
  quoteText: {
    fontSize: 10,
    color: 'rgba(255, 255, 255, 0.9)',
    lineHeight: 13,
    fontWeight: '500',
  },
  quoteLine: {
    width: 48,
    height: 1.5,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    marginTop: 3,
    borderRadius: 1,
  },

  /* Form Container Card */
  formCard: {
    marginHorizontal: 14,
    marginTop: -22,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 20,
    shadowColor: '#0F1E50',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(226, 232, 240, 0.8)',
  },

  field: {
    marginBottom: 16,
  },
  label: {
    fontSize: 13.5,
    fontWeight: '700',
    color: '#1E293B',
    marginBottom: 8,
  },
  required: {
    color: '#EF4444',
  },

  /* Select Card */
  selectCard: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 54,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
  },
  selectCardActive: {
    borderColor: '#2563EB',
    shadowColor: '#2563EB',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 2,
  },
  iconBadgeCircleBlue: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#EFF6FF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  iconBadgeSmBlue: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#EFF6FF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  selectContent: {
    flex: 1,
    justifyContent: 'center',
  },
  selectTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1E293B',
    lineHeight: 18,
  },
  selectSub: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '500',
    marginTop: 2,
  },

  /* Dropdown Options */
  dropdownContainer: {
    marginTop: 6,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
  },
  dropdownOption: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  dropdownOptionSelected: {
    backgroundColor: '#EFF6FF',
  },
  dropdownOptionText: {
    fontSize: 14,
    color: '#1E293B',
    fontWeight: '500',
  },
  dropdownOptionTextSelected: {
    color: '#2563EB',
    fontWeight: '700',
  },

  /* Row for Date Fields */
  row: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  halfField: {
    flex: 1,
  },
  dateCard: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 50,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    gap: 10,
  },
  dateText: {
    flex: 1,
    fontSize: 13.5,
    fontWeight: '600',
    color: '#1E293B',
  },

  /* Half Day Box */
  halfDayBox: {
    backgroundColor: '#F8FAFD',
    borderWidth: 1,
    borderColor: '#E8EEF5',
    borderRadius: 14,
    padding: 14,
  },
  halfDayMain: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  checkboxBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 10,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: '#94A3B8',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  checkboxChecked: {
    backgroundColor: '#2563EB',
    borderColor: '#2563EB',
  },
  halfDayTextCol: {
    flex: 1,
  },
  halfDayTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1E293B',
    lineHeight: 18,
  },
  halfDaySub: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },

  /* Number of Days Card */
  daysCard: {
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#DBEAFE',
    borderRadius: 14,
    paddingHorizontal: 16,
    height: 54,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  daysIconBadge: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#2563EB',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  daysContent: {
    flex: 1,
    justifyContent: 'center',
  },
  daysText: {
    fontSize: 14.5,
    fontWeight: '800',
    color: '#1D4ED8',
    letterSpacing: -0.1,
    lineHeight: 18,
  },
  daysSub: {
    fontSize: 12,
    color: '#60A5FA',
    fontWeight: '500',
    marginTop: 2,
  },

  /* Reason Card */
  textareaCard: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 28,
    position: 'relative',
  },
  textareaTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  textArea: {
    flex: 1,
    fontSize: 14,
    color: '#1E293B',
    minHeight: 58,
    textAlignVertical: 'top',
    padding: 0,
    lineHeight: 20,
  },
  charCounter: {
    position: 'absolute',
    right: 16,
    bottom: 8,
    fontSize: 12,
    color: '#94A3B8',
    fontWeight: '500',
  },

  /* Info Banner */
  infoBanner: {
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#DBEAFE',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 11,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 20,
  },
  infoText: {
    flex: 1,
    fontSize: 12,
    color: '#475569',
    fontWeight: '500',
    lineHeight: 16,
  },

  /* Submit Button */
  submitBtn: {
    height: 52,
    backgroundColor: '#2563EB',
    borderRadius: 14,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    shadowColor: '#2563EB',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 14,
    elevation: 4,
  },
  submitText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
});
