// src/screens/MyProfile/MyProfileScreen.styles.js
import { StyleSheet } from 'react-native';
import { colors, spacing, radius } from '../../theme/theme';

export default StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  scrollContent: { paddingHorizontal: spacing.lg, paddingBottom: spacing.xxl },
  profileCard: { alignItems: 'center', paddingVertical: spacing.xxl, marginBottom: spacing.lg, position: 'relative' },
  cardHeaderRightEdit: { position: 'absolute', top: 12, right: 12, zIndex: 10 },
  name: { fontSize: 22, fontWeight: '800', color: colors.textPrimary, marginTop: spacing.md },
  role: { color: colors.textSecondary, marginTop: 4 },
  idChip: {
    backgroundColor: colors.infoBg,
    borderRadius: radius.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    marginTop: spacing.md,
  },
  idText: { color: colors.primary, fontWeight: '700', fontSize: 13 },
  statusCard: { marginBottom: spacing.lg },
  statusRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  statusLabel: { fontSize: 16, fontWeight: '700', color: colors.textPrimary },
  infoCard: { marginBottom: spacing.lg },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textMuted,
    letterSpacing: 0.5,
    marginBottom: spacing.md,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  editBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#E7EEFF',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  editBtnText: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '700',
  },
  actionBtnGroup: {
    flexDirection: 'row',
    gap: 8,
  },
  cancelBtn: {
    backgroundColor: colors.background,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  cancelBtnText: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '600',
  },
  saveBtn: {
    backgroundColor: colors.primary,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 8,
  },
  saveBtnText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  editFormContainer: { width: '100%', 
    gap: spacing.xs || 4,
   },
  inputField: {
    marginBottom: 8,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
    marginBottom: 4,
  },
  textInput: {
    height: 42,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm || 8,
    paddingHorizontal: 12,
    fontSize: 14,
    color: colors.textPrimary,
    backgroundColor: colors.surface,
  },
  infoRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: spacing.sm },
  infoLabel: { color: colors.textSecondary },
  infoValue: { color: colors.textPrimary, fontWeight: '600' },
  infoValueLink: { color: colors.primary, fontWeight: '700' },
  logoutBtn: {
    backgroundColor: colors.dangerBg,
    borderRadius: radius.pill,
    paddingVertical: spacing.lg,
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  logoutText: { color: colors.danger, fontWeight: '800', fontSize: 16 },
});
