// src/screens/MyProfile/MyProfileScreen.styles.js
import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#EEF4FB',
  },
  scrollContent: {
    paddingBottom: 110,
  },

  /* Header Gradient Banner - Flush to top */
  headerBanner: {
    backgroundColor: '#0066FF',
    paddingTop: Platform.OS === 'ios' ? 44 : 20,
    paddingHorizontal: 20,
    paddingBottom: 48,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    position: 'relative',
    overflow: 'hidden',
  },
  decorCircle1: {
    position: 'absolute',
    top: -30,
    right: -20,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
  },
  decorCircle2: {
    position: 'absolute',
    bottom: -30,
    left: -20,
    width: 170,
    height: 170,
    borderRadius: 85,
    backgroundColor: 'rgba(255, 255, 255, 0.09)',
  },
  backBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 14,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.3,
  },
  headerSubtitle: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.88)',
    marginTop: 4,
    fontWeight: '400',
  },

  /* Main Profile Hero Card - Exact Reference with Image 2 */
  profileHeroCard: {
    marginHorizontal: 14,
    marginTop: -26,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingVertical: 22,
    paddingHorizontal: 16,
    alignItems: 'center',
    shadowColor: '#0F1E50',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.07,
    shadowRadius: 20,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(226, 232, 240, 0.85)',
    position: 'relative',
    overflow: 'hidden',
  },
  cardWaveLeft1: {
    position: 'absolute',
    top: -30,
    left: -40,
    width: 200,
    height: 220,
    borderRadius: 100,
    backgroundColor: 'rgba(191, 219, 254, 0.45)',
  },
  cardWaveLeft2: {
    position: 'absolute',
    top: 20,
    left: -30,
    width: 140,
    height: 180,
    borderRadius: 70,
    backgroundColor: 'rgba(147, 197, 253, 0.3)',
  },
  cardWaveRight1: {
    position: 'absolute',
    bottom: -40,
    right: -50,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(191, 219, 254, 0.4)',
  },
  cardWaveRight2: {
    position: 'absolute',
    bottom: -10,
    right: -30,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: 'rgba(147, 197, 253, 0.25)',
  },
  editBtnWrap: {
    position: 'absolute',
    top: 14,
    right: 14,
    zIndex: 5,
  },
  editBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#EEF5FF',
    borderWidth: 1,
    borderColor: 'rgba(0, 102, 255, 0.12)',
    paddingHorizontal: 13,
    paddingVertical: 5,
    borderRadius: 20,
  },
  editBtnText: {
    color: '#0066FF',
    fontSize: 13,
    fontWeight: '700',
  },
  saveCancelGroup: {
    flexDirection: 'row',
    gap: 6,
  },
  cancelBtn: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: 11,
    paddingVertical: 5,
    borderRadius: 16,
  },
  cancelBtnText: {
    color: '#64748B',
    fontSize: 12.5,
    fontWeight: '600',
  },
  saveBtn: {
    backgroundColor: '#0066FF',
    paddingHorizontal: 13,
    paddingVertical: 5,
    borderRadius: 16,
  },
  saveBtnText: {
    color: '#FFFFFF',
    fontSize: 12.5,
    fontWeight: '700',
  },

  /* Avatar with Camera Badge */
  avatarWrap: {
    position: 'relative',
    width: 82,
    height: 82,
    marginVertical: 4,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
  },
  avatarCircle: {
    width: 82,
    height: 82,
    borderRadius: 41,
    backgroundColor: '#DBEAFE',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#0066FF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 3,
  },
  avatarText: {
    fontSize: 28,
    fontWeight: '800',
    color: '#0066FF',
  },
  cameraBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 27,
    height: 27,
    borderRadius: 13.5,
    backgroundColor: '#0066FF',
    borderWidth: 2.5,
    borderColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
  },
  name: {
    fontSize: 19.5,
    fontWeight: '800',
    color: '#0F172A',
    marginTop: 4,
    marginBottom: 2,
    zIndex: 2,
  },
  role: {
    fontSize: 13.5,
    color: '#64748B',
    fontWeight: '500',
    marginBottom: 9,
    zIndex: 2,
  },
  idChip: {
    backgroundColor: '#E8F2FE',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 4,
    zIndex: 2,
  },
  idText: {
    color: '#0066FF',
    fontWeight: '700',
    fontSize: 13,
  },

  /* Employment Status Card */
  statusCard: {
    marginHorizontal: 14,
    marginTop: 14,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(226, 232, 240, 0.8)',
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#0F1E50',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
    elevation: 2,
  },
  statusLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  iconBadge42: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: '#EFF6FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  statusTitle: {
    fontSize: 14.5,
    fontWeight: '700',
    color: '#0F172A',
  },
  statusSub: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  statusPillInactive: {
    backgroundColor: '#FEE2E2',
    borderWidth: 1,
    borderColor: '#FCA5A5',
  },
  statusDotInactive: {
    backgroundColor: '#EF4444',
  },
  statusTextInactive: {
    color: '#DC2626',
  },
  statusPill: {
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 999,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#16A34A',
  },
  statusText: {
    color: '#15803D',
    fontSize: 13,
    fontWeight: '700',
  },

  /* Section Cards (Job & Contact Info) */
  sectionCard: {
    marginHorizontal: 14,
    marginTop: 14,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(226, 232, 240, 0.8)',
    padding: 18,
    shadowColor: '#0F1E50',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
    elevation: 2,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1E3A8A',
    letterSpacing: 0.3,
  },
  sectionSub: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  rowsContainer: {
    borderWidth: 1,
    borderColor: '#E8EEF5',
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
  },
  dataRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 11,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  rowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  miniIconBadge: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#EFF6FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  rowLabel: {
    fontSize: 13,
    color: '#64748B',
    fontWeight: '500',
  },
  rowValue: {
    fontSize: 13.5,
    fontWeight: '700',
    color: '#0F172A',
  },
  rowValueLink: {
    color: '#0066FF',
  },

  /* Logout Button */
  logoutBtn: {
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FEE2E2',
    borderRadius: 14,
    height: 50,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 14,
  },
  logoutLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  logoutText: {
    color: '#EF4444',
    fontSize: 15,
    fontWeight: '700',
  },

  /* Edit Form Inputs */
  editFormContainer: {
    width: '100%',
    marginTop: 14,
  },
  inputField: {
    marginBottom: 12,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748B',
    marginBottom: 4,
  },
  textInput: {
    height: 42,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    paddingHorizontal: 12,
    fontSize: 14,
    color: '#0F172A',
    backgroundColor: '#FFFFFF',
  },
});
