// src/screens/HolidayCalendar/HolidayCalendarScreen.styles.js
import { StyleSheet, Dimensions } from 'react-native';
import { colors, spacing } from '../../theme/theme';

export default StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F4F7FC',
  },
  headerBanner: {
    backgroundColor: '#0066FF',
    paddingHorizontal: spacing.lg,
    paddingTop: 22,
    paddingBottom: 24,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    shadowColor: '#0066FF',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.28,
    shadowRadius: 18,
    elevation: 8,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  headerTextWrap: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 21,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.3,
  },
  headerSubtitle: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.9)',
    marginTop: 4,
  },
  headerCalendarIllustration: {
    width: 84,
    height: 76,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calWrapper: {
    width: 62,
    height: 56,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    position: 'relative',
    shadowColor: '#002D80',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 5,
  },
  calSpiralRings: {
    position: 'absolute',
    top: -7,
    left: 8,
    right: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  calRing: {
    width: 4.5,
    height: 12,
    borderRadius: 2.25,
    backgroundColor: '#BFDBFE',
  },
  calBody: {
    flex: 1,
    borderRadius: 12,
    overflow: 'hidden',
  },
  calHeaderBar: {
    height: 14,
    backgroundColor: '#3B82F6',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
  },
  calGrid: {
    padding: 5,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    justifyContent: 'center',
  },
  calGridCell: {
    width: 12,
    height: 11,
    borderRadius: 2.5,
    backgroundColor: 'rgba(191, 219, 254, 0.85)',
  },
  bellBadge: {
    position: 'absolute',
    bottom: -6,
    right: -8,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#0066FF',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
  },
  pillBarContainer: {
    paddingVertical: 12,
  },
  scrollContent: {
    paddingBottom: 90,
  },
  monthSection: {
    marginHorizontal: spacing.lg,
    marginBottom: spacing.lg,
    borderRadius: 20,
    backgroundColor: '#F0F6FE',
    borderWidth: 1,
    borderColor: '#E0ECFB',
    overflow: 'hidden',
    shadowColor: '#0046B4',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 3,
  },
  monthHeaderBar: {
    backgroundColor: '#1877F2',
    paddingHorizontal: 16,
    paddingVertical: 11,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  monthTitleText: {
    fontSize: 14.5,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.6,
  },
  monthCountBadge: {
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  monthCountText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  monthCardsContainer: {
    padding: 10,
    gap: 10,
  },
  holidayCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 12,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 1,
  },
  holidayCardHighlight: {
    borderColor: '#3B82F6',
    borderWidth: 1.5,
  },
  holidayRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  dateBlock: {
    width: 58,
    height: 58,
    borderRadius: 12,
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#DBEAFE',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dateBlockSunday: {
    backgroundColor: '#FFF1F2',
    borderColor: '#FFE4E6',
  },
  dateNumText: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1D4ED8',
    letterSpacing: -0.5,
  },
  dateDayText: {
    fontSize: 11.5,
    fontWeight: '600',
    color: '#475569',
    marginTop: 2,
  },
  cardDivider: {
    width: 1,
    height: 36,
    backgroundColor: '#E2E8F0',
    marginHorizontal: 12,
  },
  cardInfo: {
    flex: 1,
    paddingRight: 6,
  },
  nameText: {
    fontSize: 14.5,
    fontWeight: '700',
    color: '#0F172A',
  },
  subText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#64748B',
    marginTop: 2,
  },
  tagBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
  },
  tagBadgeNational: {
    backgroundColor: '#DBEAFE',
    borderColor: '#BFDBFE',
  },
  tagBadgeFestival: {
    backgroundColor: '#F3E8FF',
    borderColor: '#E9D5FF',
  },
  tagText: {
    fontSize: 12,
    fontWeight: '700',
  },
  tagTextNational: {
    color: '#1D4ED8',
  },
  tagTextFestival: {
    color: '#7E22CE',
  },
});
